BotSpiel/Controllers/OutboundOrderLinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using BotSpiel.DataAccess.Models;
using BotSpiel.Services;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using NonFactors.Mvc.Grid;


namespace BotSpiel
{

    public class OutboundOrderLinesController : Controller
    {

/*
-- =============================================
-- Author:		<BotSpiel>

-- Description:	<Description>

This class ....

*/
 
        private readonly IOutboundOrderLinesService _outboundorderlinesService;

        public OutboundOrderLinesController(IOutboundOrderLinesService outboundorderlinesService )
        {
            _outboundorderlinesService = outboundorderlinesService;
        }

        // GET: OutboundOrderLines
        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            var outboundorderlines = _outboundorderlinesService.Index();
            return View(outboundorderlines.ToList());
        }

        [Authorize]
        [HttpGet]
        public ActionResult IndexExport()
        {
            return View(CreateExportableGrid());
        }

        [Authorize]
        [HttpGet]
        public PartialViewResult IndexGrid()
        {
            var outboundorderlines = _outboundorderlinesService.Index();
            return PartialView("IndexGrid", outboundorderlines.ToList());
        }

        [Authorize]
        [HttpGet]
        public FileContentResult ExportIndex()
        {
            using (ExcelPackage package = new ExcelPackage())
            {
                Int32 row = 2;
                Int32 col = 1;

                package.Workbook.Worksheets.Add("Data");
                IGrid<OutboundOrderLines> grid = CreateExportableGrid();
                ExcelWorksheet sheet = package.Workbook.Worksheets["Data"];

                foreach (IGridColumn column in grid.Columns)
                {
                    sheet.Cells[1, col].Value = column.Title;
                    sheet.Column(col++).Width = 18;
                }

                foreach (IGridRow<OutboundOrderLines> gridRow in grid.Rows)
                {
                    col = 1;
                    foreach (IGridColumn column in grid.Columns)
                        sheet.Cells[row, col++].Value = column.ValueFor(gridRow);

                    row++;
                }

                return File(package.GetAsByteArray(), "application/unknown", "ExportOutboundOrderLines.xlsx");
            }
        }

        private IGrid<OutboundOrderLines> CreateExportableGrid()
        {
            IGrid<OutboundOrderLines> grid = new Grid<OutboundOrderLines>(_outboundorderlinesService.Index().ToList());
            grid.ViewContext = new ViewContext { HttpContext = HttpContext };
            grid.Query = Request.Query;
				grid.Columns.Add(model => model.sOutboundOrderLine).Titled("Outbound Order Line").Sortable(true).Filterable(true).MultiFilterable(true);
				grid.Columns.Add(model => model.OutboundOrders.sOutboundOrder).Titled("Outbound Order").Sortable(true).Filterable(true);
				grid.Columns.Add(model => model.sOrderLineReference).Titled("Order Line Reference").Sortable(true).Filterable(true).MultiFilterable(true);
				grid.Columns.Add(model => model.Materials.sMaterial).Titled("Material").Sortable(true).Filterable(true);
				grid.Columns.Add(model => model.sBatchNumber).Titled("Batch Number").Sortable(true).Filterable(true).MultiFilterable(true);
				grid.Columns.Add(model => model.sSerialNumber).Titled("Serial Number").Sortable(true).Filterable(true).MultiFilterable(true);
				grid.Columns.Add(model => model.nBaseUnitQuantityOrdered).Titled("Base Unit Quantity Ordered").Sortable(true).Filterable(true);
				grid.Columns.Add(model => model.nBaseUnitQuantityShipped).Titled("Base Unit Quantity Shipped").Sortable(true).Filterable(true);
				grid.Columns.Add(model => model.Statuses.sStatus).Titled("Status").Sortable(true).Filterable(true).MultiFilterable(true);
				grid.Columns.Add(model => model.dtCreatedAt).Titled("Created At").Sortable(true).Filterable(true);
				grid.Columns.Add(model => model.dtChangedAt).Titled("Changed At").Sortable(true).Filterable(true);
				grid.Columns.Add(model => model.sCreatedBy).Titled("Created By").Sortable(true).Filterable(true).MultiFilterable(true);
				grid.Columns.Add(model => model.sChangedBy).Titled("Changed By").Sortable(true).Filterable(true).MultiFilterable(true);

            grid.Pager = new GridPager<OutboundOrderLines>(grid);
            grid.Processors.Add(grid.Pager);
            grid.Pager.PageSizes = new Dictionary<Int32, String> { { 0, "All" }, { 5, "5" }, { 10, "10" }, { 15, "15" }, { 20, "20" }, { 40, "40" }, { 100, "100" } };
            grid.Pager.ShowPageSizes = true;
            grid.Pager.RowsPerPage = 20;

            return grid;
        }


        // GET: OutboundOrderLines/Details/1
        [Authorize]
        public ActionResult Details(long id)
        {
            return View(_outboundorderlinesService.Get(id));
        }

        // GET: OutboundOrderLines/Create
        
        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
			ViewBag.ixMaterial = new SelectList(_outboundorderlinesService.selectMaterials().Select( x => new { x.ixMaterial, x.sMaterial }), "ixMaterial", "sMaterial");
			ViewBag.ixOutboundOrder = new SelectList(_outboundorderlinesService.selectOutboundOrders().Select( x => new { x.ixOutboundOrder, x.sOutboundOrder }), "ixOutboundOrder", "sOutboundOrder");
			ViewBag.ixStatus = new SelectList(_outboundorderlinesService.selectStatuses().Select( x => new { x.ixStatus, x.sStatus }), "ixStatus", "sStatus");

            return View();
        }

        // POST: OutboundOrderLines/Create 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("ixOutboundOrderLine,sOutboundOrderLine,ixOutboundOrder,sOrderLineReference,ixMaterial,sBatchNumber,sSerialNumber,nBaseUnitQuantityOrdered,nBaseUnitQuantityShipped,ixStatus")] OutboundOrderLinesPost outboundorderlines)
        {
            if (ModelState.IsValid)
            {
                outboundorderlines.UserName = User.Identity.Name;
                _outboundorderlinesService.Create(outboundorderlines);
                return RedirectToAction("Index");
            }
			ViewBag.ixMaterial = new SelectList(_outboundorderlinesService.selectMaterials().Select( x => new { x.ixMaterial, x.sMaterial }), "ixMaterial", "sMaterial");
			ViewBag.ixOutboundOrder = new SelectList(_outboundorderlinesService.selectOutboundOrders().Select( x => new { x.ixOutboundOrder, x.sOutboundOrder }), "ixOutboundOrder", "sOutboundOrder");
			ViewBag.ixStatus = new SelectList(_outboundorderlinesService.selectStatuses().Select( x => new { x.ixStatus, x.sStatus }), "ixStatus", "sStatus");

            return View(outboundorderlines);
        }

        //Custom Code Start | Removed Block 

        [Authorize]
        [HttpGet]
        public ActionResult CreateWithID(long id)
        {
            ViewBag.ixMaterial = new SelectList(_outboundorderlinesService.selectMaterials().Select(x => new { x.ixMaterial, x.sMaterial }), "ixMaterial", "sMaterial");
            ViewBag.ixOutboundOrder = new SelectList(_outboundorderlinesService.selectOutboundOrders().Where(x => x.ixOutboundOrder == id).Select(x => new { x.ixOutboundOrder, x.sOutboundOrder }), "ixOutboundOrder", "sOutboundOrder");
            ViewBag.ixStatus = new SelectList(_outboundorderlinesService.selectStatuses().Select(x => new { x.ixStatus, x.sStatus }), "ixStatus", "sStatus");

            return View();
        }

        // POST: OutboundOrderLines/Create 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateWithID([Bind("ixOutboundOrderLine,sOutboundOrderLine,ixOutboundOrder,sOrderLineReference,ixMaterial,sBatchNumber,sSerialNumber,nBaseUnitQuantityOrdered,nBaseUnitQuantityShipped,ixStatus")] OutboundOrderLinesPost outboundorderlines)
        {
            if (ModelState.IsValid)
            {
                outboundorderlines.UserName = User.Identity.Name;
                _outboundorderlinesService.Create(outboundorderlines);
                return RedirectToAction("Edit", "OutboundOrders", new { id = outboundorderlines.ixOutboundOrder });
            }
            ViewBag.ixMaterial = new SelectList(_outboundorderlinesService.selectMaterials().Select(x => new { x.ixMaterial, x.sMaterial }), "ixMaterial", "sMaterial");
            ViewBag.ixOutboundOrder = new SelectList(_outboundorderlinesService.selectOutboundOrders().Select(x => new { x.ixOutboundOrder, x.sOutboundOrder }), "ixOutboundOrder", "sOutboundOrder");
            ViewBag.ixStatus = new SelectList(_outboundorderlinesService.selectStatuses().Select(x => new { x.ixStatus, x.sStatus }), "ixStatus", "sStatus");

            return View(outboundorderlines);
        }

        //Custom Code End			


        // GET: OutboundOrderLines/Edit/1
        [Authorize]
        [HttpGet]
        public ActionResult Edit(long id)
        {
            OutboundOrderLinesPost outboundorderlines = _outboundorderlinesService.GetPost(id);
            if (outboundorderlines == null)
            {
                return NotFound();
            }
			ViewBag.ixMaterial = new SelectList(_outboundorderlinesService.selectMaterials().Select( x => new { x.ixMaterial, x.sMaterial }), "ixMaterial", "sMaterial", outboundorderlines.ixMaterial);
			ViewBag.ixOutboundOrder = new SelectList(_outboundorderlinesService.selectOutboundOrders().Select( x => new { x.ixOutboundOrder, x.sOutboundOrder }), "ixOutboundOrder", "sOutboundOrder", outboundorderlines.ixOutboundOrder);

BotSpiel/Controllers/StatusesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using BotSpiel.DataAccess.Models;
using BotSpiel.Services;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using NonFactors.Mvc.Grid;


namespace BotSpiel
{

    public class StatusesController : Controller
    {

/*
-- =============================================
-- Author:		<BotSpiel>

-- Description:	<Description>

This class ....

*/
 
        private readonly IStatusesService _statusesService;

        public StatusesController(IStatusesService statusesService )
        {
            _statusesService = statusesService;
        }

        // GET: Statuses
        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            var statuses = _statusesService.Index();
            return View(statuses.ToList());
        }

        [Authorize]
        [HttpGet]
        public ActionResult IndexExport()
        {
            return View(CreateExportableGrid());
        }

        [Authorize]
        [HttpGet]
        public PartialViewResult IndexGrid()
        {
            var statuses = _statusesService.Index();
            return PartialView("IndexGrid", statuses.ToList());
        }

        [Authorize]
        [HttpGet]
        public FileContentResult ExportIndex()
        {
            using (ExcelPackage package = new ExcelPackage())
            {
                Int32 row = 2;
                Int32 col = 1;

                package.Workbook.Worksheets.Add("Data");
                IGrid<Statuses> grid = CreateExportableGrid();
                ExcelWorksheet sheet = package.Workbook.Worksheets["Data"];

                foreach (IGridColumn column in grid.Columns)
                {
                    sheet.Cells[1, col].Value = column.Title;
                    sheet.Column(col++).Width = 18;
                }

                foreach (IGridRow<Statuses> gridRow in grid.Rows)
                {
                    col = 1;
                    foreach (IGridColumn column in grid.Columns)
                        sheet.Cells[row, col++].Value = column.ValueFor(gridRow);

                    row++;
                }

                return File(package.GetAsByteArray(), "application/unknown", "ExportStatuses.xlsx");
            }
        }

        private IGrid<Statuses> CreateExportableGrid()
        {
            IGrid<Statuses> grid = new Grid<Statuses>(_statusesService.Index().ToList());
            grid.ViewContext = new ViewContext { HttpContext = HttpContext };
            grid.Query = Request.Query;
				grid.Columns.Add(model => model.sStatus).Titled("Status").Sortable(true).Filterable(true).MultiFilterable(true);
				grid.Columns.Add(model => model.sStatusCode).Titled("Status Code").Sortable(true).Filterable(true).MultiFilterable(true);
				grid.Columns.Add(model => model.dtCreatedAt).Titled("Created At").Sortable(true).Filterable(true);
				grid.Columns.Add(model => model.dtChangedAt).Titled("Changed At").Sortable(true).Filterable(true);
				grid.Columns.Add(model => model.sCreatedBy).Titled("Created By").Sortable(true).Filterable(true).MultiFilterable(true);
				grid.Columns.Add(model => model.sChangedBy).Titled("Changed By").Sortable(true).Filterable(true).MultiFilterable(true);

            grid.Pager = new GridPager<Statuses>(grid);
            grid.Processors.Add(grid.Pager);
            grid.Pager.PageSizes = new Dictionary<Int32, String> { { 0, "All" }, { 5, "5" }, { 10, "10" }, { 15, "15" }, { 20, "20" }, { 40, "40" }, { 100, "100" } };
            grid.Pager.ShowPageSizes = true;
            grid.Pager.RowsPerPage = 20;

            return grid;
        }


        // GET: Statuses/Details/1
        [Authorize]
        public ActionResult Details(long id)
        {
            return View(_statusesService.Get(id));
        }

        // GET: Statuses/Create
        
        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }

        // POST: Statuses/Create 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("ixStatus,sStatus,sStatusCode")] StatusesPost statuses)
        {
            if (ModelState.IsValid)
            {
                statuses.UserName = User.Identity.Name;
                _statusesService.Create(statuses);
                return RedirectToAction("Index");
            }

            return View(statuses);
        }

        // GET: Statuses/Edit/1
        [Authorize]
        [HttpGet]
        public ActionResult Edit(long id)
        {
            StatusesPost statuses = _statusesService.GetPost(id);
            if (statuses == null)
            {
                return NotFound();
            }

            return View(statuses);
        }

        // POST: Statuses/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind("ixStatus,sStatus,sStatusCode")] StatusesPost statuses)
        {
            if (ModelState.IsValid)
            {
                statuses.UserName = User.Identity.Name;
                _statusesService.Edit(statuses);
                return RedirectToAction("Index");
            }

            return View(statuses);
        }


        // GET: Statuses/Delete/1
        [Authorize]
        [HttpGet]
        public ActionResult Delete(long id)
        {
            return View(_statusesService.Get(id));
        }

        // POST: Statuses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            StatusesPost statuses = _statusesService.GetPost(id);
            statuses.UserName = User.Identity.Name;
            _statusesService.Delete(statuses);
            return RedirectToAction("Index");
        } 

        [AcceptVerbs("Get", "Post")]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public ActionResult MultiRowDelete(string Ids)
        {
            string validationResponse = "";
            string[] sIDs = Ids.Split("|");
            List<long> iDs = new List<long>();
            long nID;
            string sStatus;

            StatusesPost statuses;

            sIDs.ToList()
                .ForEach(s =>
                    {
                        if (long.TryParse(s, out nID))
                        {
                            sStatus = _statusesService.Get(nID).sStatus;
                            if (!_statusesService.VerifyStatusDeleteOK(nID, sStatus).Any())
                            {
                                statuses = _statusesService.GetPost(nID);
                                statuses.UserName = User.Identity.Name;
                                _statusesService.Delete(statuses);
                                iDs.Add(nID);
                            }
                        }
                    }
                );

            iDs.ForEach(n => validationResponse = validationResponse + ", " + n.ToString());

            return Json(validationResponse);
        }

        [AcceptVerbs("Get","Post")]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult VerifyStatus(long ixStatus, string sStatus)
        {
            string validationResponse = "";

            if (!_statusesService.VerifyStatusUnique(ixStatus, sStatus))
            {
                validationResponse = $"Status {sStatus} already exists.";
            }
            if (validationResponse != "")
            return Json(validationResponse);
            else
            return Json(true);
        }



    }
}
 

BotSpiel/Views/OutboundOrderLines/Create.cshtml
@model BotSpiel.DataAccess.Models.OutboundOrderLinesPost

@{
    ViewBag.Title = "Create Outbound Order Lines";
}
<br>
<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Outbound Order Lines</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.sOrderLineReference, "Order Line Reference", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sOrderLineReference, new { htmlAttributes = new { @class = "form-control", @placeholder = "Required" } })
                @Html.ValidationMessageFor(model => model.sOrderLineReference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
			@Html.ActionLink("Material ID", "Index", "Materials", "", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ixMaterial", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ixMaterial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sBatchNumber, "Batch Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sBatchNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sBatchNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sSerialNumber, "Serial Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sSerialNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sSerialNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nBaseUnitQuantityOrdered, "Base Unit Quantity Ordered", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nBaseUnitQuantityOrdered, new { htmlAttributes = new { @class = "form-control", @placeholder = "Required" } })
                @Html.ValidationMessageFor(model => model.nBaseUnitQuantityOrdered, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nBaseUnitQuantityShipped, "Base Unit Quantity Shipped", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nBaseUnitQuantityShipped, new { htmlAttributes = new { @class = "form-control", @placeholder = "Required" } })
                @Html.ValidationMessageFor(model => model.nBaseUnitQuantityShipped, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
			@Html.ActionLink("Status ID", "Index", "Statuses", "", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ixStatus", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ixStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grid", "Index")
</div>

@section Scripts {
}

 

BotSpiel/Views/OutboundOrderLines/CreateWithID.cshtml
@model BotSpiel.DataAccess.Models.OutboundOrderLinesPost

@{
    ViewBag.Title = "Create Outbound Order Lines";
}
<br>
<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Outbound Order Lines</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.ActionLink("Outbound Order ID", "Index", "OutboundOrders", "", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ixOutboundOrder", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ixOutboundOrder, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.sOrderLineReference, "Order Line Reference", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.sOrderLineReference, new { htmlAttributes = new { @class = "form-control", @placeholder = "Required" } })
            @Html.ValidationMessageFor(model => model.sOrderLineReference, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.ActionLink("Material ID", "Index", "Materials", "", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ixMaterial", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ixMaterial, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.sBatchNumber, "Batch Number", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.sBatchNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.sBatchNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.sSerialNumber, "Serial Number", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.sSerialNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.sSerialNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nBaseUnitQuantityOrdered, "Base Unit Quantity Ordered", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nBaseUnitQuantityOrdered, new { htmlAttributes = new { @class = "form-control", @placeholder = "Required" } })
            @Html.ValidationMessageFor(model => model.nBaseUnitQuantityOrdered, "", new { @class = "text-danger" })
        </div>
    </div>
    @*//Custom Code Start | Removed Block*@
    @*<div class="form-group">
        @Html.LabelFor(model => model.nBaseUnitQuantityShipped, "Base Unit Quantity Shipped", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nBaseUnitQuantityShipped, new { htmlAttributes = new { @class = "form-control", @placeholder = "Required" } })
            @Html.ValidationMessageFor(model => model.nBaseUnitQuantityShipped, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.ActionLink("Status ID", "Index", "Statuses", "", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ixStatus", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ixStatus, "", new { @class = "text-danger" })
        </div>
    </div>*@
    @*//Custom Code End*@
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Grid", "Index")
</div>

@section Scripts {
}

 

BotSpiel/Views/OutboundOrderLines/Index.cshtml
@model IEnumerable<BotSpiel.DataAccess.Models.OutboundOrderLines>

@{
    ViewBag.Title = "Index Outbound Order Lines";
}
<br>
<h2>Outbound Order Lines</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @Html.ActionLink(" | Grid Export", "IndexExport")
</p>

<p>    
    <button type="button" id="refresh-grid" class="btn btn-default content-refresh">Refresh Grid</button>
    <button type="button" class="btn btn-default delete-rows" onclick="deleteRows('OutboundOrderLines')">Delete Selected Rows</button>
</p>

@Html.AjaxGrid(Url.Action("IndexGrid"), new { id = "outboundorderlines-ajax-grid" })
 

BotSpiel/Views/OutboundOrderLines/IndexExport.cshtml
@model IGrid<BotSpiel.DataAccess.Models.OutboundOrderLines>

@{
    ViewBag.Title = "Index Outbound Order Lines Export";
}
<br>
<h2>Outbound Order Lines Export</h2>

<p>
    <a href="@(Url.Action("ExportIndex") + ViewContext.HttpContext.Request.QueryString)">Export</a>
    @Html.ActionLink(" | Grid", "Index")
</p>

@(new HtmlGrid<BotSpiel.DataAccess.Models.OutboundOrderLines>(Html, Model))
 