BotSpiel/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using BotSpiel.DataAccess.Models;
using BotSpiel.Services;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using NonFactors.Mvc.Grid;


namespace BotSpiel
{

    public class InvoicesController : Controller
    {

/*
-- =============================================
-- Author:		<BotSpiel>

-- Description:	<Description>

This class ....

*/
 
        private readonly IInvoicesService _invoicesService;

        public InvoicesController(IInvoicesService invoicesService )
        {
            _invoicesService = invoicesService;
        }

        // GET: Invoices
        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            var invoices = _invoicesService.Index();
            return View(invoices.ToList());
        }

        [Authorize]
        [HttpGet]
        public ActionResult IndexExport()
        {
            return View(CreateExportableGrid());
        }

        [Authorize]
        [HttpGet]
        public PartialViewResult IndexGrid()
        {
            var invoices = _invoicesService.Index();
            return PartialView("IndexGrid", invoices.ToList());
        }

        [Authorize]
        [HttpGet]
        public FileContentResult ExportIndex()
        {
            using (ExcelPackage package = new ExcelPackage())
            {
                Int32 row = 2;
                Int32 col = 1;

                package.Workbook.Worksheets.Add("Data");
                IGrid<Invoices> grid = CreateExportableGrid();
                ExcelWorksheet sheet = package.Workbook.Worksheets["Data"];

                foreach (IGridColumn column in grid.Columns)
                {
                    sheet.Cells[1, col].Value = column.Title;
                    sheet.Column(col++).Width = 18;
                }

                foreach (IGridRow<Invoices> gridRow in grid.Rows)
                {
                    col = 1;
                    foreach (IGridColumn column in grid.Columns)
                        sheet.Cells[row, col++].Value = column.ValueFor(gridRow);

                    row++;
                }

                return File(package.GetAsByteArray(), "application/unknown", "ExportInvoices.xlsx");
            }
        }

        private IGrid<Invoices> CreateExportableGrid()
        {
            IGrid<Invoices> grid = new Grid<Invoices>(_invoicesService.Index().ToList());
            grid.ViewContext = new ViewContext { HttpContext = HttpContext };
            grid.Query = Request.Query;
				grid.Columns.Add(model => model.sInvoice).Titled("Invoice").Sortable(true).Filterable(true).MultiFilterable(true);
				grid.Columns.Add(model => model.Purchases.sPurchase).Titled("Purchase").Sortable(true).Filterable(true);
				grid.Columns.Add(model => model.dtCreatedAt).Titled("Created At").Sortable(true).Filterable(true);
				grid.Columns.Add(model => model.dtChangedAt).Titled("Changed At").Sortable(true).Filterable(true);
				grid.Columns.Add(model => model.sCreatedBy).Titled("Created By").Sortable(true).Filterable(true).MultiFilterable(true);
				grid.Columns.Add(model => model.sChangedBy).Titled("Changed By").Sortable(true).Filterable(true).MultiFilterable(true);

            grid.Pager = new GridPager<Invoices>(grid);
            grid.Processors.Add(grid.Pager);
            grid.Pager.PageSizes = new Dictionary<Int32, String> { { 0, "All" }, { 5, "5" }, { 10, "10" }, { 15, "15" }, { 20, "20" }, { 40, "40" }, { 100, "100" } };
            grid.Pager.ShowPageSizes = true;
            grid.Pager.RowsPerPage = 20;

            return grid;
        }


        // GET: Invoices/Details/1
        [Authorize]
        public ActionResult Details(long id)
        {
            return View(_invoicesService.Get(id));
        }

        // GET: Invoices/Create
        
        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
			ViewBag.ixPurchase = new SelectList(_invoicesService.selectPurchases().Select( x => new { x.ixPurchase, x.sPurchase }), "ixPurchase", "sPurchase");

            return View();
        }

        // POST: Invoices/Create 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("ixInvoice,sInvoice,ixPurchase")] InvoicesPost invoices)
        {
            if (ModelState.IsValid)
            {
                invoices.UserName = User.Identity.Name;
                _invoicesService.Create(invoices);
                return RedirectToAction("Index");
            }
			ViewBag.ixPurchase = new SelectList(_invoicesService.selectPurchases().Select( x => new { x.ixPurchase, x.sPurchase }), "ixPurchase", "sPurchase");

            return View(invoices);
        }

        // GET: Invoices/Edit/1
        [Authorize]
        [HttpGet]
        public ActionResult Edit(long id)
        {
            InvoicesPost invoices = _invoicesService.GetPost(id);
            if (invoices == null)
            {
                return NotFound();
            }
			ViewBag.ixPurchase = new SelectList(_invoicesService.selectPurchases().Select( x => new { x.ixPurchase, x.sPurchase }), "ixPurchase", "sPurchase", invoices.ixPurchase);

            return View(invoices);
        }

        // POST: Invoices/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind("ixInvoice,sInvoice,ixPurchase")] InvoicesPost invoices)
        {
            if (ModelState.IsValid)
            {
                invoices.UserName = User.Identity.Name;
                _invoicesService.Edit(invoices);
                return RedirectToAction("Index");
            }
			ViewBag.ixPurchase = new SelectList(_invoicesService.selectPurchases().Select( x => new { x.ixPurchase, x.sPurchase }), "ixPurchase", "sPurchase", invoices.ixPurchase);

            return View(invoices);
        }


        // GET: Invoices/Delete/1
        [Authorize]
        [HttpGet]
        public ActionResult Delete(long id)
        {
            return View(_invoicesService.Get(id));
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            InvoicesPost invoices = _invoicesService.GetPost(id);
            invoices.UserName = User.Identity.Name;
            _invoicesService.Delete(invoices);
            return RedirectToAction("Index");
        } 

        [AcceptVerbs("Get", "Post")]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public ActionResult MultiRowDelete(string Ids)
        {
            string validationResponse = "";
            string[] sIDs = Ids.Split("|");
            List<long> iDs = new List<long>();
            long nID;
            string sInvoice;

            InvoicesPost invoices;

            sIDs.ToList()
                .ForEach(s =>
                    {
                        if (long.TryParse(s, out nID))
                        {
                            sInvoice = _invoicesService.Get(nID).sInvoice;
                            if (!_invoicesService.VerifyInvoiceDeleteOK(nID, sInvoice).Any())
                            {
                                invoices = _invoicesService.GetPost(nID);
                                invoices.UserName = User.Identity.Name;
                                _invoicesService.Delete(invoices);
                                iDs.Add(nID);
                            }
                        }
                    }
                );

            iDs.ForEach(n => validationResponse = validationResponse + ", " + n.ToString());

            return Json(validationResponse);
        }

        [AcceptVerbs("Get","Post")]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult VerifyInvoice(long ixInvoice, string sInvoice)
        {
            string validationResponse = "";

            if (!_invoicesService.VerifyInvoiceUnique(ixInvoice, sInvoice))
            {
                validationResponse = $"Invoice {sInvoice} already exists.";
            }
            if (validationResponse != "")
            return Json(validationResponse);
            else
            return Json(true);
        }



    }
}
 

BotSpiel/Views/InvoicePurchaseLineAmounts/Create.cshtml
@model BotSpiel.DataAccess.Models.InvoicePurchaseLineAmountsPost

@{
    ViewBag.Title = "Create Invoice Purchase Line Amounts";
}
<br>
<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoice Purchase Line Amounts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
			@Html.ActionLink("Invoice ID", "Index", "Invoices", "", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ixInvoice", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ixInvoice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
			@Html.ActionLink("Purchase Line ID", "Index", "PurchaseLines", "", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ixPurchaseLine", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ixPurchaseLine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mAmount, "Amount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mAmount, new { htmlAttributes = new { @class = "form-control", @placeholder = "Required" } })
                @Html.ValidationMessageFor(model => model.mAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
			@Html.ActionLink("Currency ID", "Index", "Currencies", "", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ixCurrency", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ixCurrency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grid", "Index")
</div>

@section Scripts {
}

 

BotSpiel/Views/InvoicePurchaseLineAmounts/Delete.cshtml
@using System.Linq;
@using System.Collections.Generic;
@using BotSpiel.Services;
@using BotSpiel.Services.Utilities;
@inject IInvoicePurchaseLineAmountsService _invoicepurchaselineamountsService
@model BotSpiel.DataAccess.Models.InvoicePurchaseLineAmounts

@{
    ViewBag.Title = "Delete Invoice Purchase Line Amounts";
}

@{
    string conCat = "";
    List<string> existInEntities = new List<string>();
    bool DeleteOK = true;
    existInEntities = _invoicepurchaselineamountsService.VerifyInvoicePurchaseLineAmountDeleteOK(Model.ixInvoicePurchaseLineAmount, Model.sInvoicePurchaseLineAmount);
    if (existInEntities.Any()) { DeleteOK = false; }
}


@if (DeleteOK)
{

<br>
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice Purchase Line Amounts</h4>
    <hr />
    <dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.ixInvoicePurchaseLineAmount)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.ixInvoicePurchaseLineAmount)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.sInvoicePurchaseLineAmount)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.sInvoicePurchaseLineAmount)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Invoices.sInvoice)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Invoices.sInvoice)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.PurchaseLines.sPurchaseLine)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.PurchaseLines.sPurchaseLine)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.mAmount)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.mAmount)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Currencies.sCurrency)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Currencies.sCurrency)
		</dd>
 
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Grid", "Index")
        </div>
    }
</div>
}
else
{
    <br>
    <h2>Delete</h2>

    <h3>The InvoicePurchaseLineAmount @Model.sInvoicePurchaseLineAmount cannot be deleted. It is referenced by the following entities:</h3>
    <hr />
    @foreach (var entity in existInEntities)
    {
        conCat = String.Join(" ", StringSplitters.SplitCamelCase(@entity.ToString()));
        <h4>@Html.ActionLink(@conCat.ToString(), "Index", @entity.ToString())</h4>
        <hr />
    }

    <h3>If you want to delete the InvoicePurchaseLineAmount, delete the dependent references first.</h3>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Grid", "Index")
        </div>
    }

}
 

BotSpiel/Views/InvoicePurchaseLineAmounts/Details.cshtml
@model BotSpiel.DataAccess.Models.InvoicePurchaseLineAmounts

@{
    ViewBag.Title = "Details Invoice Purchase Line Amounts";
}
<br>
<h2>Details</h2>

<div>
    <h4>Invoice Purchase Line Amounts</h4>
    <hr />
    <dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.ixInvoicePurchaseLineAmount)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.ixInvoicePurchaseLineAmount)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.sInvoicePurchaseLineAmount)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.sInvoicePurchaseLineAmount)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Invoices.sInvoice)
		</dt>
		<dd>
			@Html.ActionLink(Model.Invoices.sInvoice, "Details", "Invoices", new { id = Model.ixInvoice }, null)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.PurchaseLines.sPurchaseLine)
		</dt>
		<dd>
			@Html.ActionLink(Model.PurchaseLines.sPurchaseLine, "Details", "PurchaseLines", new { id = Model.ixPurchaseLine }, null)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.mAmount)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.mAmount)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Currencies.sCurrency)
		</dt>
		<dd>
			@Html.ActionLink(Model.Currencies.sCurrency, "Details", "Currencies", new { id = Model.ixCurrency }, null)
		</dd>


    </dl>
</div>
<p>    @Html.ActionLink("Edit", "Edit", new { id = Model.ixInvoicePurchaseLineAmount }) |
	@Html.ActionLink("Delete", "Delete", new { id = Model.ixInvoicePurchaseLineAmount }) |
    @Html.ActionLink("Grid", "Index")
</p>

 

BotSpiel/Views/InvoicePurchaseLineAmounts/Edit.cshtml
@model BotSpiel.DataAccess.Models.InvoicePurchaseLineAmountsPost 

@{
    ViewBag.Title = "Edit Invoice Purchase Line Amounts";
}
<br>
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoice Purchase Line Amounts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ixInvoicePurchaseLineAmount)

        <div class="form-group">
			@Html.ActionLink("Invoice ID", "Index", "Invoices", "", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ixInvoice", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ixInvoice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
			@Html.ActionLink("Purchase Line ID", "Index", "PurchaseLines", "", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ixPurchaseLine", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ixPurchaseLine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mAmount, "Amount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
			@Html.ActionLink("Currency ID", "Index", "Currencies", "", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ixCurrency", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ixCurrency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Grid", "Index")
</div>

@section Scripts {
}


 

BotSpiel/Views/InvoicePurchaseLineAmounts/Index.cshtml
@model IEnumerable<BotSpiel.DataAccess.Models.InvoicePurchaseLineAmounts>

@{
    ViewBag.Title = "Index Invoice Purchase Line Amounts";
}
<br>
<h2>Invoice Purchase Line Amounts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @Html.ActionLink(" | Grid Export", "IndexExport")
</p>

<p>    
    <button type="button" id="refresh-grid" class="btn btn-default content-refresh">Refresh Grid</button>
    <button type="button" class="btn btn-default delete-rows" onclick="deleteRows('InvoicePurchaseLineAmounts')">Delete Selected Rows</button>
</p>

@Html.AjaxGrid(Url.Action("IndexGrid"), new { id = "invoicepurchaselineamounts-ajax-grid" })
 

BotSpiel/Views/InvoicePurchaseLineAmounts/IndexExport.cshtml
@model IGrid<BotSpiel.DataAccess.Models.InvoicePurchaseLineAmounts>

@{
    ViewBag.Title = "Index Invoice Purchase Line Amounts Export";
}
<br>
<h2>Invoice Purchase Line Amounts Export</h2>

<p>
    <a href="@(Url.Action("ExportIndex") + ViewContext.HttpContext.Request.QueryString)">Export</a>
    @Html.ActionLink(" | Grid", "Index")
</p>

@(new HtmlGrid<BotSpiel.DataAccess.Models.InvoicePurchaseLineAmounts>(Html, Model))
 

BotSpiel/Views/InvoicePurchaseLineAmounts/IndexGrid.cshtml
@using System.Linq;
@using System.Collections.Generic;
@using BotSpiel.Services;
@inject IInvoicePurchaseLineAmountsService _invoicepurchaselineamountsService
@model IEnumerable<BotSpiel.DataAccess.Models.InvoicePurchaseLineAmounts>

@{
	List<SelectListItem> queryCurrencies = new List<SelectListItem>();
	queryCurrencies.AddRange(_invoicepurchaselineamountsService.selectCurrencies().ToList().OrderBy(de => de.sCurrency).Select(de => new SelectListItem() { Text = de.sCurrency, Value = de.sCurrency.ToString()}));
	List<SelectListItem> queryInvoices = new List<SelectListItem>();
	queryInvoices.AddRange(_invoicepurchaselineamountsService.selectInvoices().ToList().OrderBy(de => de.sInvoice).Select(de => new SelectListItem() { Text = de.sInvoice, Value = de.sInvoice.ToString()}));
	List<SelectListItem> queryPurchaseLines = new List<SelectListItem>();
	queryPurchaseLines.AddRange(_invoicepurchaselineamountsService.selectPurchaseLines().ToList().OrderBy(de => de.sPurchaseLine).Select(de => new SelectListItem() { Text = de.sPurchaseLine, Value = de.sPurchaseLine.ToString()}));

}


@(Html
        .Grid(Model)
        .Build(columns =>
        {
				columns.Add(model => Html.CheckBox("Check_" + model.ixInvoicePurchaseLineAmount, new { @class = "rowCheckBox" })).Titled(Html.CheckBox("CheckAll", new { @onclick = "toggleAll()" }));
				columns.Add(model => model.ixInvoicePurchaseLineAmount).Titled("Details").Encoded(false).RenderedAs(item => Html.ActionLink("Details", "Details", new { id = item.ixInvoicePurchaseLineAmount }, new { @class = "modal-link" }));
				columns.Add(model => model.ixInvoicePurchaseLineAmountEdit).Titled("Edit").Encoded(false).RenderedAs(item => Html.ActionLink("Edit", "Edit", new { id = item.ixInvoicePurchaseLineAmount }, new { @class = "modal-link" }));
				columns.Add(model => model.sInvoicePurchaseLineAmount).Titled("Invoice Purchase Line Amount").Sortable(true).Filterable(true);
				columns.Add(model => model.Invoices.sInvoice).Titled("Invoice").Sortable(true).Filterable(true).MultiFilterable(true).WithFilterOptions(queryInvoices);
				columns.Add(model => model.PurchaseLines.sPurchaseLine).Titled("Purchase Line").Sortable(true).Filterable(true).MultiFilterable(true).WithFilterOptions(queryPurchaseLines);
				columns.Add(model => model.mAmount).Titled("Amount").Sortable(true).Filterable(true);
				columns.Add(model => model.Currencies.sCurrency).Titled("Currency").Sortable(true).Filterable(true).MultiFilterable(true).WithFilterOptions(queryCurrencies);
				columns.Add(model => model.dtCreatedAt).Titled("Created At").Sortable(true).Filterable(true);
				columns.Add(model => model.dtChangedAt).Titled("Changed At").Sortable(true).Filterable(true);
				columns.Add(model => model.sCreatedBy).Titled("Created By").Sortable(true).Filterable(true);
				columns.Add(model => model.sChangedBy).Titled("Changed By").Sortable(true).Filterable(true);
        })
        .Empty("No data found")
        .Id("invoicepurchaselineamounts-ajax-grid")
        .Pageable(pager =>
        {
            pager.PageSizes = new Dictionary<Int32, String> { { 0, "All" }, { 5, "5" }, { 10, "10" }, { 15, "15" }, { 20, "20" }, { 40, "40" }, { 100, "100" } };
            pager.ShowPageSizes = true;
            pager.RowsPerPage = 20;
        })
        .Css("css-classes")
        .AppendCss("table-hover")
 )


 